[platformio]
default_envs = bedside_esp32dev_v1

[env:bedside_esp32dev_v1]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  chris--a/Keypad@^3.1.1

build_flags =
  -DCORE_DEBUG_LEVEL=3
