[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; If your bedside board is ESP32-S3, change board to:
; board = esp32-s3-devkitc-1

lib_deps =
  bblanchon/ArduinoJson@^6.21.5
  adafruit/Adafruit GFX Library@^1.11.9
  adafruit/Adafruit SSD1306@^2.5.10
  chris--a/Keypad@^3.1.1
  marcoschwartz/LiquidCrystal_I2C@^1.1.4

build_flags =
  -DCORE_DEBUG_LEVEL=3
